### ISSUE TITLE
Non-VR can´t Play on vive-only Server

### ISSUE THREAD

**Issue by Kili-97** [jrbudda/Vivecraft_115#8]
Non-VR can´t Play on vive-only Server

is there a solution for this problem

**Comment by Espergium** [comment]
Your question solves itself. The server is VR only.

**Comment by jrbudda** [comment]
I can understand how you might assume the vive-only setting applies to the non-vr version. The description in the config.yml instructions is ambiguous and I will clarify it. There is no way to use the spigot plugin to force users to use the non-vr companion instead of vanilla. Setting vive-only restricts the server to VR users only.
